config/routes.rb
Rails.application.routes.draw do
  get "sign_up/:source" => "users#new", :as => "sign_up"
  post "sign_up" => "users#create_guest", :as => "create_guest"
  get "sign_in" => "sessions#new", :as => "sign_in"
  post "sign_in" => "sessions#create"
  delete "sign_out" => "sessions#delete"
  post "/users/:source" => "users#create"
  post "/users" => "users#create"
  get "walls/:id" => "walls#index"
  get "hang_it" => "hang_it#index"

  root to: "home#index"

  resources :users, except: :create do
    resources :pictures, :except => [:update, :destroy]
  end

  resources :arrangements

  resources :pictures, :only => [:update, :destroy]

  resources :frames
  resources :walls

  get "/search" => "search#index", :as => "search"

  post "share_picture/:id" => "shares#share_picture", :as => "share_picture"
  delete "unshare_picture/:id" => "shares#delete_share", :as => "unshare_picture"

end

app/models/home.rb
class Home < ActiveRecord::Base

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @pictures = Picture.all
  end

  def new

  end
end

app/views/home/index.html.erb
<script src="//cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.10.4/typeahead.bundle.min.js"></script>

<section class="enter">
  <article class="enter-button">
    <% if current_user %>
      <img src="/assets/vector-frame.png" class="vector-frame">
      <div class="homepage-link"><%= link_to "Visualize your art in different spaces.  Frame-it, stage-it & share-it.", user_pictures_path(current_user) %></div>
    <% else %>
      <img src="/assets/vector-frame.png" class="vector-frame">
      <div class="homepage-link"><%= link_to "Visualize your art in different spaces.  Frame-it, stage-it & share-it.", create_guest_path, method: :post%></div>
    <% end %>
  </article>
</section>

<div class="hr-line"><hr></div>

<h1 class="title-tag">Explore Art</h1>

<br>

<div class="three-columns">
  <div class="three-column-one"></div>
  <div class="three-column-two"></div>
  <div class="three-column-three"></div>
</div>

<div class="cards">
  <% @pictures.each_with_index do |picture, index| %>

    <% if index % 3 == 0 %>
      <script>
        $('.three-column-one').append("<div class='card card-on-homepage'><div class='card-image'><img src='<%= picture.image.url %>' alt=''></div><div class='card-header'></div></div>")
      </script>
      <% elsif index % 3 == 1 %>
      <script>
     $('.three-column-two').append("<div class='card card-on-homepage'>" +
        "<div class='card-image'>" +
          "<img src='<%= picture.image.url %>' alt=''>" +
          "</div>" +
        "<div class='card-header'>" +

          "</div>" +
        "</div>")
      </script>
    <% elsif index % 3 == 2 %>
      <script>
        $('.three-column-three').append("<div class='card card-on-homepage'>" +
          "<div class='card-image'>" +
          "<img src='<%= picture.image.url %>' alt=''>" +
          "</div>" +
          "<div class='card-header'>" +

          "</div>" +
          "</div>")
      </script>
      <% end %>
  <% end %>
</div>
</div>

<script>
  var bestFrames = new Bloodhound({
    datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value'),
    queryTokenizer: Bloodhound.tokenizers.whitespace,
    remote: '/search?q=%QUERY',
  });

  bestFrames.initialize();

  $('#searchfield').typeahead(null, {
    source: bestFrames.ttAdapter()
  });
</script>