config/routes.rb
Rails.application.routes.draw do
  get "sign_up/:source" => "users#new", :as => "sign_up"
  post "sign_up" => "users#create_guest", :as => "create_guest"
  get "sign_in" => "sessions#new", :as => "sign_in"
  post "sign_in" => "sessions#create"
  delete "sign_out" => "sessions#delete"
  post "/users/:source" => "users#create"
  post "/users" => "users#create"
  get "walls/:id" => "walls#index"
  get "hang_it" => "hang_it#index"

  root to: "home#index"

  resources :users, except: :create do
    resources :pictures, :except => [:update, :destroy]
  end

  resources :arrangements

  resources :pictures, :only => [:update, :destroy]

  resources :frames
  resources :walls

  get "/search" => "search#index", :as => "search"

  post "share_picture/:id" => "shares#share_picture", :as => "share_picture"
  delete "unshare_picture/:id" => "shares#delete_share", :as => "unshare_picture"

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :user

  validates_presence_of :image, :height, :width, :description
  validates_numericality_of :height, :width
end

app/controllers/pictures_controller.rb
require 'rvg/rvg'

class PicturesController < ApplicationController
  include Magick

  def index
    @picture = Picture.new
    @wall = Wall.new
    @shares = Share.select(:picture_id).map(&:picture_id)

  end

  def create

    picture_creator = PictureCreator.new(session, params)

    @picture = Picture.new

    if picture_creator.save
      flash[:notice] = "Picture successfully uploaded"
      redirect_to user_pictures_path(current_user)
    else
      flash[:notice] = "Please select a picture to upload"
      render user_pictures_path(current_user)
    end

  end

  def destroy
    @share = Share.where(:picture_id => params[:id])
    @share.destroy_all if @share
    @picture = Picture.find(params[:id])
    @picture.destroy

    respond_to do |format|
      format.json { render :json => {}}
    end
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])
    @picture.update(
      :description=>params[:description]
    )
    respond_to do |format|
      format.json { render :json => {} }
    end
  end

  def show
    @picture = Picture.find(params[:id])
  end

  private

  def allowed_parameters
    params.require(:picture).permit(@file_name, @url, @user_id)
  end
end

app/views/pictures/_picture_form.html.erb
<div id="upload-picture-form">
  <%= form_for [current_user, @picture], :html => {:multipart => true} do |f| %>
    <% if @picture.errors.any? %>
      <div class="error_messages">
        <ul>
          <% for message in @picture.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <article class="form-fields">
      <p>
        <%= f.file_field :image, :required => true %>
      </p>
      <p>
        <%= f.label :height %>
        <%= f.number_field :height, :required => true, placeholder: "ex: 30" %>
      </p>
      <p>
        <%= f.label :width %>
        <%= f.number_field :width, :required => true, placeholder: "ex: 20"%>
      </p>
      <p>
        <%= f.label :description %>
        <%= f.text_field :description, :required => true, placeholder: "ex: self-portrait" %>
      </p>
      <%= f.submit "Upload Picture" %>
    </article>
  <% end %>
</div>

app/views/pictures/_wall_form.html.erb
<div id="upload-wall-form">
  <%= form_for @wall, :html => {:multipart => true} do |f| %>
    <% if @wall.errors.any? %>
      <div class="error_messages">
        <ul>
          <% for message in @wall.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <article class="form-fields">
      <p>
        <%= f.file_field :image, :required => true %>
      </p>
      <p>
        <%= f.label :name, "height (inches)" %>
        <%= f.number_field :height, :required => true, placeholder: "ex: 64" %>
      </p>
      <p>
        <%= f.label :name, "width (inches)" %>
        <%= f.number_field :width, :required => true, placeholder: "ex: 45" %>
      </p>
      <p>
        <%= f.label :description %>
        <%= f.text_field :description, :required => true, placeholder: "ex: wall above couch" %>
      </p>

      <%= f.submit "Create Wall" %>
    </article>
  <% end %>
</div>

app/views/pictures/edit.html.erb
<%= form_for @picture, :html => {:multipart => true} do |f| %>

  <p>
    <%= f.label :file_name %>
    <%= f.text_field :file_name %>
  </p>

  <%= f.submit "Update Picture" %>
<% end %>

app/views/pictures/index.html.erb
<div class="container">
  <section class="picture-form">
    <article class="form-fields">
      <p id="picture-form-button"><%= link_to "Select a picture to frame" %><em class='right-triangle'> &#9654;</em>
        <em class='down-triangle'>&#9660;</em></p>

      <p id="wall-form-button"><%= link_to "Create a wall to hang your picture on" %>
        <em class='right-triangle'> &#9654;</em><em class='down-triangle'>&#9660;</em></p>
    </article>
    <%= render "pictures/picture_form" %>
    <%= render "pictures/wall_form" %>
  </section>
</div>

<ul class="accordion-tabs">
  <li class="tab-header-and-content">
    <a href="#" class="is-active tab-link">Pictures</a>

    <div class="tab-content is-open">
      <div class="cards">
        <% current_user.pictures.each do |picture| %>
          <div class="card" data-id="<%= picture.id %>">
            <div class="card-image">
              <img src="<%= picture.image.url %>" alt="">
            </div>
            <div class="card-header">
              <em class="picture-description"><%= picture.description %></em>
            </div>
            <div class="card-stats">
              <ul data-id="<%= picture.id %>">
                <li><span class="delete-picture"><em>&#10008;</em> </span></li>
                <li><span><%= link_to "frame it", user_picture_path(current_user, picture) %></span></li>
                <li><span><%= link_to "hang it", walls_path(picture.id) %></span></li>
                <% if @shares.include?(picture.id) == true %>
                  <li id="<%= picture.id %>">
                    <span><%= link_to "unshare", unshare_picture_path(picture), class: "share-it-link unshare" %></span>
                  </li>
                <% else %>
                  <li>
                    <span><%= link_to "share it", share_picture_path(picture), class: "share-it-link share" %></span>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </li>
  <li class="tab-header-and-content">
    <%= render "walls/saved_arrangements"%>
  </li>
  <li class="tab-header-and-content">
    <a href="#" class="tab-link">Favorite Frames</a>

    <div class="tab-content">
      <% if current_user.walls == [] %>
        <div class="nothing-created_message">
          <h4>You have not favorited any frames</h4>
        </div>
      <% end %>
    </div>
  </li>

  <li class="tab-header-and-content">
    <a href="#" class="tab-link">Walls</a>

    <div class="tab-content">
      <div class="cards">

        <% current_user.walls.each do |wall| %>
          <div class="card">
            <div class="card-image">
              <img src="<%= wall.image.url %>" alt="">
            </div>
            <div class="card-header">
              <%= wall.description %>
            </div>
            <div class="card-stats">

            <ul data-id="<%= wall.id %>">
              <li><span class="delete-wall"><em>&#10008;</em> </span></li>
            </ul>

            </div>
          </div>
        <% end %>
        <% if current_user.walls == [] %>
          <div class="nothing-created_message">
            <h4>You have not created any walls</h4>
          </div>
        <% end %>
      </div>

    </div>
  </li>
</ul>

app/views/pictures/show.html.erb
<container ng-app="frameApp">
  <div ng-controller="FrameController">

    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-beta.18/angular.min.js"></script>

    <section class="work-table" >

      <div style="overflow: hidden; position: absolute; margin-right: -50%; top: 50%; left: 50%; width: 400px; transform: translate(-50%, -50%); height: 300px">
        <%= image_tag @picture.image.url, :class =>"picture" %>
      </div>
      <%= image_tag "", {class: "frames", "ng-src"=> "{{currentImage()}}"}%>

    </section>
    <div class="frame-button">
    <button ng-click="previousFrame()">&larr;</button>
    <button ng-click="nextFrame()">&rarr;</button>
    </div>
  </div>
</container>


<script>

  angular.module('frameApp', [])
    .controller('FrameController', ['$scope', '$http', function($scope, $http) {
      $scope.frames = [];
      $http.get('/frames.json').success(function(data){
        $scope.frames = data;
      });

      $scope.frameIndex = 0;

      $scope.currentImage = function() {
        if ($scope.frames.length > 0) {
          return $scope.frames[$scope.frameIndex].image.url;
        }
      };

      $scope.nextFrame = function() {
        if ($scope.frameIndex + 1 >= $scope.frames.length) {
          $scope.frameIndex = 0;
        } else {
          $scope.frameIndex += 1;
        }
      };

      $scope.previousFrame = function() {
        if ($scope.frameIndex - 1 < 0) {
          $scope.frameIndex = $scope.frames.length - 1;
        } else {
          $scope.frameIndex -= 1;
        }
      };

      $scope.frameWidth = function() {
        if ($scope.frames.length > 0) {
          return parseInt($scope.frames[$scope.frameIndex].inner_width);
        }
        else {
          return 1
        }
      };

      $scope.frameHeight = function() {
        if ($scope.frames.length > 0) {
          return parseInt($scope.frames[$scope.frameIndex].inner_height);
        }
        else {
          return 1
        }
      };

      $scope.pixelsPerInch = function() {
        if ($scope.frames.length > 0) {
          return 400 / $scope.frameWidth();
        }
      };

      $scope.frameHeightPixels = function() {
        if ($scope.frames.length > 0) {
          return $scope.pixelsPerInch() * $scope.frameHeight();
        }
        else {
          return 1
        }
      };

    }]);
</script>