config/routes.rb
Rails.application.routes.draw do
  get "sign_up/:source" => "users#new", :as => "sign_up"
  post "sign_up" => "users#create_guest", :as => "create_guest"
  get "sign_in" => "sessions#new", :as => "sign_in"
  post "sign_in" => "sessions#create"
  delete "sign_out" => "sessions#delete"
  post "/users/:source" => "users#create"
  post "/users" => "users#create"
  get "walls/:id" => "walls#index"
  get "hang_it" => "hang_it#index"

  root to: "home#index"

  resources :users, except: :create do
    resources :pictures, :except => [:update, :destroy]
  end

  resources :arrangements

  resources :pictures, :only => [:update, :destroy]

  resources :frames
  resources :walls

  get "/search" => "search#index", :as => "search"

  post "share_picture/:id" => "shares#share_picture", :as => "share_picture"
  delete "unshare_picture/:id" => "shares#delete_share", :as => "unshare_picture"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def signed_in?
    current_user.present? || guest_user.present?
  end

  def current_user
    if session[:user_id]
      User.find_by(id: session[:user_id])
    else
      User.find_by(id: session[:guest_user_id])
    end
  end

  def guest_user
    if session[:guest_user_id]
      User.find_by(id: session[:guest_user_id])
    end
  end

  helper_method :current_user, :signed_in?, :guest_user

  private

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_card.html.erb
<div class="cards">
  <div class="card">
    <div class="card-image">
      <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/mountains.png" alt="">
    </div>
    <div class="card-header">
      First Card
    </div>
    <div class="card-copy">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga, officiis sunt neque facilis culpa molestiae necessitatibus delectus veniam provident.</p>
    </div>
    <div class="card-stats">
      <ul>
        <li>98<span>Items</span></li>
        <li>298<span>Things</span></li>
        <li>923<span>Objects</span></li>
      </ul>
    </div>
  </div>
</div>

app/views/application/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="flash-<%= key %>">
    <span class="alert"><%= value %></span>
  </div>
<% end %>

app/views/application/_navbar.html.erb
<header class="navigation">
  <div class="navigation-wrapper">
    <a href="/">
      <h1 class="logo">frame-it</h1>
    </a>

    <a href="" class="navigation-menu-button" id="js-mobile-menu">MENU</a>
    <div class="nav">
      <ul id="navigation-menu">
        <% if signed_in? %>
          <% if guest_user %>
            <li class="nav-link">Signed in as guest</li>
            <li class="nav-link"><%= link_to "Sign Up", sign_up_path("guest_upload") %></li>
            <li class="nav-link"><%= link_to "Sign In", sign_in_path %></li>
          <% else %>
            <li class="nav-link"><%= link_to "Sell Frames", frames_path %></li>
            <li class="nav-link "><%= link_to "Your Gallery", user_pictures_path(current_user) %></li>
            <li class="nav-link ">Signed in as <%=current_user.email%></li>
            <li class="nav-link"><%= link_to "Sign Out", sign_out_path, method: :delete %></li>
          <% end %>
        <% else %>
          <li class="nav-link"><%= link_to "Sign Up", sign_up_path("nil") %></li>
          <li class="nav-link"><%= link_to "Sign In", sign_in_path %></li>
        <% end %>
      </ul>
    </div>
  </div>

</header>